### ISSUE TITLE
bpf_skb_pull_data with len 0

### ISSUE THREAD

**Issue by bogushevich** [pouriyajamshidi/flat#12]
Hi, Pouriya.
It's really great and helpful post: https://thegraynode.io/posts/bpf_flat_part2/ . Thank you. 
But I found one mistake.  
"Inside the function body, we do our first sanity check by pulling the data of each packet in a linear region of memory by calling the bpf_skb_pull_data, **passing it the packet’s metadata and a 0 to signify that we need the entire packet**."
Passing 0 just make writable linear part, it doesn't pull at all: https://github.com/torvalds/linux/commit/bdb2bc7599298ebb677e40fc92b1fa9e69e05098  
You can check it here: https://github.com/torvalds/linux/blob/master/net/core/filter.c#L1855

This issue about post, not a repository. I just can't find another way to share with you this information.
Thank you again for you blog!

**Comment by pouriyajamshidi** [comment]
Hi Maxim @bogushevich,

I really appreciate the time and effort you put into finding me this way and providing this awesome explanation!

I have corrected the post and gave you a shout-out

https://thegraynode.io/posts/bpf_flat_part2/#second-update---26-october-2023
